version: '3.8'
services:
  db:
    build:
      context: ./server
      dockerfile: Dockerfile.postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
