version: '3.1'

services:
  redis:
    image: redis:latest  # Use the Redis image from Docker Hub
    ports:
      - "6379:6379"  # Map the default Redis port on the container to the host
    volumes:
      - redis_data:/data 

volumes:
  redis_data:
