name: Cypress Tests

on:
  push:
    branches:
      - Purvil-Personal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./web

      - name: Run Cypress tests
        run: npm run cypress:run
        working-directory: ./web  # Specify the working directory here as well
