name: Cypress Tests

on:
  push:
    branches:
      - Purvil-Personal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set working directory
        run: cd scalable-microblogging-platform\web
        working-directory: scalable-microblogging-platform\web

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run
