name: CI/CD Pipeline with Docker Image Build

on:
  push:
    branches: [ CI_CD ]
  pull_request:
    branches: [ CI_CD ]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Backend Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: purvil1699/backend-image
        tags: latest
        registry: docker.io
        dockerfile: ./server/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Frontend Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: purvil1699/frontend-image
        tags: latest
        registry: docker.io
        dockerfile: ./web/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}