name: CI/CD Pipeline Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '16'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

  server-build-and-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Install server dependencies
        run: npm install
        working-directory: ./server

  web-build-and-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Install web dependencies
        run: npm install
        working-directory: ./web

  Jest_test:
    needs: [server-build-and-test, web-build-and-test]
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: npm test
        working-directory: ./server
